apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: database    # Added namespace
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk  # 'rootpassword' in base64
  mysql-password: cGFzc3dvcmQ=           # 'password' in base64